
[functions.send-attendance-code]
enabled = true
verify_jwt = true
import_map = "./functions/send-attendance-code/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-attendance-code/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-attendance-code/*.html" ]

[functions.send-meeting-invitations]
enabled = true
verify_jwt = true
import_map = "./functions/send-meeting-invitations/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-meeting-invitations/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-meeting-invitations/*.html" ]
